apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api_users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api_users
    spec:
      containers:
      - name: api_users
        image: leviatan/api_users
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: api_users
  labels:
    app: api_users
spec:
  selector:
    app: api_users
  ports:
    - protocol: TCP
      port: 8500
  type: LoadBalancer