apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-users
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-users
    spec:
      containers:
      - name: api-users
        image: api_users:latest
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: api-users
  labels:
    app: api-users
spec:
  selector:
    app: api-users
  ports:
    - protocol: TCP
      port: 8500
  type: LoadBalancer